# Starter pipeline
- task: UiPathDeploy@2
  inputs:
    orchestratorConnection: 'UiPath Orchestrator Connection'
    packagesPath: 'C:\Users\niranjan_mahtole\Desktop\Hello.World.Project.1.0.1.nupkg'
    folderName: 'Shared'
    entryPoints: 'Main.xaml'
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
